'use client';
import Sidebar from '../components/Sidebar';
import { useDQContext } from '../context/DQContext';

export default function RulesPage() {
  const { analysisResult } = useDQContext();

  const parseLLMRules = (text) => {
    // Simple parser if the text is markdown
    return text.split('\n').map((line, i) => {
      line = line.trim();
      if (line.startsWith('**') || line.match(/^[0-9]+\./) || line.startsWith('###')) {
        return <h4 key={i} style={{ marginTop: 16, color: 'var(--primary-300)' }}>{line.replace(/\*/g, '').replace('###', '')}</h4>;
      } else if (line.startsWith('-') || line.startsWith('*')) {
        return <li key={i} style={{ marginLeft: 20, marginBottom: 8 }}>{line.replace(/^[-*]/, '').replace(/\*\*/g, '')}</li>;
      } else if (line !== '') {
        return <p key={i} style={{ marginBottom: 12 }}>{line.replace(/\*\*/g, '')}</p>;
      }
      return null;
    });
  };

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">
        <header className="top-bar">
          <div>
            <h1>AI Rules Engine</h1>
            <p>Business rules generated by local Gemma LLM using schema metadata only</p>
          </div>
          <span className="badge badge-success">
            <span className="badge-dot"></span>
            Gemma 4 Connected
          </span>
        </header>

        {/* Privacy Notice */}
        <div className="panel" style={{ padding: '14px 24px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ fontSize: '1.1rem' }}>🔒</span>
          <p style={{ margin: 0, fontSize: '0.82rem' }}>
            <strong style={{ color: 'var(--emerald-400)' }}>Zero Data Exposure:</strong> Only the column names and types are sent to the local Gemma model. No actual row-level data leaves the system boundary.
          </p>
        </div>

        {!analysisResult ? (
          <div style={{ textAlign: 'center', padding: '80px 20px' }}>
            <div style={{ fontSize: '3rem', marginBottom: 16 }}>🤖</div>
            <h2 style={{ color: 'var(--slate-300)', marginBottom: 8 }}>Ready for AI Analysis</h2>
            <p>Upload a dataset on the Dashboard to invoke the local Gemma LLM.</p>
          </div>
        ) : (
          <div className="panel">
            <div className="panel-header">
              <h2>Proposed Business Rules for <code style={{ color: 'var(--primary-300)', background: 'rgba(99,102,241,0.1)', padding: '2px 8px', borderRadius: 4, fontSize: '0.9rem' }}>{analysisResult.filename}</code></h2>
              <span className="badge badge-primary">AI Generated</span>
            </div>
            <div className="rules-list" style={{ padding: 24 }}>
              <div style={{ lineHeight: '1.6', color: 'var(--slate-200)', background: 'rgba(0,0,0,0.2)', padding: 24, borderRadius: 12, border: '1px solid var(--slate-700)' }}>
                {parseLLMRules(analysisResult.llm_rules)}
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
